name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check packages structure
        run: |
          echo "Checking workspace packages:"
          pnpm list --depth=0
          echo "Checking app package:"
          ls -la packages/app/

      - name: Build React App
        run: |
          pnpm -F @hanghae-plus/shopping exec vite build
          cp ./packages/app/dist/index.html ./packages/app/dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./packages/app/dist" # React 빌드 결과물 경로

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
